### ISSUE TITLE
About how to use the model

### ISSUE THREAD

**Issue by JyhWind** [tchayintr/rvnn-pytorch#2]
I am a rookie of python and it is hard for me to understand the code or paper completely. Can you tell me how to use the trained model to predict new data? Thank you!

**Comment by JyhWind** [comment]
By the way, I will be appreciated if you can tell me the form of data. (for example, **_(3 (2 ``) (3 (2 (2 Extreme) (2 Ops)) (3 (2 '') (4 (4 (3 exceeds) (2 expectations)) (2 .)))))_** means what?)

**Comment by tchayintr** [comment]
> Can you tell me how to use the trained model to predict new data? Thank you!

You can train your own model by using this code but I am not sure if 'to predict new data' you have mentioned is to decode new data to get tree output...
If it is the case, this code doesn't provide the decoding function. However you can revise the code by using the prediction labels from the following code
[recursive_nn.py](https://github.com/tchayintr/rvnn-pytorch/blob/14d37a2859820265decb900dca9a391873158af6/src/recursive_nn.py) to implement your own prediction function.


> By the way, I will be appreciated if you can tell me the form of data. (for example, (3 (2 ``) (3 (2 (2 Extreme) (2 Ops)) (3 (2 '') (4 (4 (3 exceeds) (2 expectations)) (2 .))))) means what?)

It is basically a hierarchical (tree) structure from SSTb dataset, where a number represents the sentimental class from very negative to very positive (0-4) for each node.
